Add append method for AssetLabels
opencost/opencost pull request #1166
Opened 2022-04-19 14:33 UTC by biancaburtoiu

## What does this PR change?
This PR adds an `append(labels map[string]string)` method to be used on objects of type `AssetLabels`. 

## Does this PR relate to any other PRs?
Yes, this PR must be merged before https://github.com/kubecost/kubecost-cost-model/pull/718 

## How will this PR impact users?
Not directly

## Does this PR address any GitHub or Zendesk issues?
N/A

## How was this PR tested?
N/A

## Does this PR require changes to documentation?
No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Kubecost release? If not, why not?
Yes

2022-04-20 17:54 UTC, nikovacevic requested changes

2022-04-20 17:54 UTC, nikovacevic commented on pkg/kubecost/asset.go
> +	if len(newLabels) > 0 {
One small nit here w/r/t Go style. Go style prefers early returns so that the critical path of code remains least indented if possible. In this case, that would be:
```go
if len(newLabels) == 0 {
    return
}

...
```

And, in fact, I think this condition is not precisely right. Would you agree that we want to append labels to an empty map? We only want to early return if the map is `nil` so that we don't panic. Let me know if you disagree!

2022-04-20 18:05 UTC, biancaburtoiu commented on pkg/kubecost/asset.go
> +	if len(newLabels) > 0 {
Re: the defensive call -- I totally agree, I missed that. Fixing it. 

Recall that `newLabels` in this case represents the account tag labels we are planning to add; if that list is somehow empty, we'll want to exit without further action. 

I actually handled the case of the AssetLabels object being nil in the caller of this method, in the [other PR](https://github.com/kubecost/kubecost-cost-model/pull/718/files): 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/22826352/164294468-ca8d8d5b-36bf-431f-9d70-d9531f68b102.png">

WDYT?

2022-04-21 00:06 UTC, nikovacevic commented on pkg/kubecost/asset.go
> +	if len(newLabels) > 0 {
Oops! I misread and thought that was the existing labels. Thank you for correcting me :sweat_smile: 

LGTM!

2022-04-21 00:07 UTC, nikovacevic approved these changes

2022-04-21 13:51 UTC, merged