allow the ability to disable writing to storage
opencost/opencost pull request #1342
Opened 2022-08-02 21:40 UTC by Sean-Holcomb

## What does this PR change?
* This PR adds a layer between the storage object and it creator which can block certain operation. In this case using an env variable ETL_STORE_READ_ONLY it will disable writes and deletes. This prevents an attached instance of kubecost from changing the store.

## Does this PR relate to any other PRs?
* 

## How will this PR impact users?
* this feature is not meant for users

## Does this PR address any GitHub or Zendesk issues?
* Closes ...

## How was this PR tested?
* Tested by setting the Environmental variable variable to true and ensuring that only loads were occurring.

## Does this PR require changes to documentation?
* Documentation to be included in the deployments repo and etl data generation repo

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
*

2022-08-16 22:58 UTC, nikovacevic approved these changes

2022-08-16 22:58 UTC, nikovacevic commented on pkg/env/costmodelenv.go
> +	ETLStoreReadOnlyMode                 = "ETL_STORE_READ_ONLY"
Agree with Bolt's comment that it's rough already having `ETL_READ_ONLY`... but this seems like making the best of a messy situation.

2022-08-19 22:22 UTC, mbolt35 requested changes
We definitely need some changes here. 

1. The `storage.Storage` APIs are not specific to ETL. They're used for shared config files and Provider Configuration storage as well. If you were to turn this on right now, then writing the updated Provider config would stop working. 
2. There's nothing in opencost that uses our ETL pipeline, so it's _really_ confusing to have ETL variables in our configuration. This seems to indicate we're leaking implementation we shouldn't be. 

My suggestion is that we make this change in our private repository, not at a core API level. You can just as easily wrap a _specific_ `storage.Storage` implementation within the ETL API (versus applying universal access rules to _all_ file storage based on an ETL specific configuration). 

Hope that makes sense, let me know if you have any questions.

2022-08-19 23:20 UTC, nikovacevic commented
Good catch, Bolt.

2022-08-19 23:56 UTC, Sean-Holcomb commented
Following @mbolt35 suggestions and moving changes to KCM

2022-08-19 23:56 UTC, closed without merging