GP3 volumes support
opencost/opencost pull request #1421
Opened 2022-10-12 10:18 UTC by AndrewChubatiuk

## What does this PR change?
Added GP3 volumes support in AWS

## How was this PR tested?
Was tested in my setup, which uses GP3

## Does this PR require changes to documentation?
No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
Have no clue how to label

2022-10-14 11:57 UTC, AjayTripathy commented
Thanks for this PR @AndrewChubatiuk . Is the most minimal set of changes to just modify aws.provider.go? I think the PR scope should be just limited to that-- we can discuss what's going on in queries.go in a separate PR or discussion.

2022-10-14 11:58 UTC, AjayTripathy requested changes

2022-10-14 11:58 UTC, AjayTripathy commented on pkg/prom/queries.go
> +package prom
Is this necessary within this PR? Happy to discuss changes here in a separate one!

2022-10-14 12:07 UTC, AndrewChubatiuk commented on pkg/prom/queries.go
> +package prom
Sorry, unintended file here

2022-10-14 12:09 UTC, AndrewChubatiuk commented on pkg/prom/queries.go
> +package prom
@AjayTripathy updated PR

2022-10-17 16:44 UTC, AjayTripathy approved these changes

2022-10-17 16:46 UTC, AjayTripathy commented on pkg/prom/queries.go
> +package prom
Thank you!

2022-10-17 16:46 UTC, merged