Always returning config values if secret not found
opencost/opencost pull request #1427
Opened 2022-10-14 12:16 UTC by duncan485

## What does this PR change?
* By always returning the configValues, we can use MSI (aadpodidentity) to authenticate for the ratecard query. This uses the already auth.NewAuthorizerFromEnvironment existing on https://github.com/opencost/opencost/blob/develop/pkg/cloud/azureprovider.go#L788. Using MSI, we'd only need the subscriptionId as config to create the NewRateCardClientWithBaseURI. However, before this PR, the subscriptionId would never be returned if the client-secret, client-id and tenant-id where not set. 

## Does this PR relate to any other PRs?
* no

## How will this PR impact users?
* A user can now also use aadpodidentity to authenticate . Only config values to be set are:
  currencyCode
  azureBillingRegion
  azureOfferDurableID
  azureSubscriptionID

## How was this PR tested?
* Build the container and run on an AKS cluster with AAD podidentity

2022-10-17 19:05 UTC, AjayTripathy commented
@Sean-Holcomb quick one if you could take a look?

2022-10-18 17:03 UTC, Sean-Holcomb requested changes
Since `azureSubscriptionID` is still a required field can we keep a check for it. Additionally I would like to see a short comment about MSI. More than happy to merge with those changes

2022-10-19 22:14 UTC, Sean-Holcomb approved these changes

2022-10-21 07:25 UTC, duncan485 commented
@AjayTripathy @Sean-Holcomb Thanks for the approval, can this one be merged ?

2022-10-21 18:01 UTC, merged