Nick/azure orphaned resources disknames
opencost/opencost pull request #1538
Opened 2022-12-07 23:45 UTC by nickcurie

## What does this PR change?
* Adds disk names to Azure's orphaned resources

## Does this PR relate to any other PRs?
* https://github.com/opencost/opencost/pull/1489

## How will this PR impact users?
* Users will see disk names

## Does this PR address any GitHub or Zendesk issues?
* 

## How was this PR tested?
* On Azure cluster

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
* v1.99

2022-12-07 23:57 UTC, nikovacevic requested changes
Just that one nil check to add! Otherwise, looks good.

2022-12-07 23:57 UTC, nikovacevic commented on pkg/cloud/azureprovider.go
> +				DiskName:    *d.Name,
Given that this is a pointer, I'm guessing there's a chance it could be `nil`. Let's check that nil, just to be safe?

```
diskName := ""
if d.Name != nil {
    diskName = *d.Name
}

...

DiskName: diskName,
```

2022-12-08 00:02 UTC, nickcurie commented on pkg/cloud/azureprovider.go
> +				DiskName:    *d.Name,
Should I do the same with region?

2022-12-08 00:17 UTC, michaelmdresser approved these changes

2022-12-08 00:35 UTC, nikovacevic approved these changes

2022-12-08 00:36 UTC, merged