Set configs in `aws.json` to empty strings
opencost/opencost pull request #2301
Opened 2023-11-10 00:06 UTC by thomasvn

## What does this PR change?
* Sets configs in `aws.json` to empty strings
* Previously, having placeholder variables there would lead Kubecost to attempt to create a cloud integration with those variables. The cloud integration would inevitably fail.

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* Cleaner install

## Does this PR address any GitHub or Zendesk issues?
* No

## How was this PR tested?
* TODO. Working on locally running a test, and also deploying an image to test.

## Does this PR require changes to documentation?
* TODO. Need to ensure that the format of the expected string is clearly documented.

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* TODO.

2023-11-10 00:57 UTC, srpomeroy approved these changes
Good call on doing the same with the spot values!

2023-11-21 17:32 UTC, nikovacevic requested changes
I think this actually breaks things IIRC -- @Sean-Holcomb do you remember? Aaron G tried this once, and it screwed up something.

2023-12-29 19:53 UTC, thomasvn commented
@nikovacevic I've tested this in our QA Nightly EKS environment and haven't run into any issues. Let me know if you'd like to take a look at the environment as well!

2024-01-02 16:24 UTC, nikovacevic commented
Pretty sure it was something related to cloud integrations. So as long as cloud integrations are working fine, no need to test in other envs. Thank you.

2024-01-02 16:24 UTC, nikovacevic approved these changes

2024-01-03 23:26 UTC, merged